version: '3.1'
services:
  web:
    volumes:
      - ".:/app"
    depends_on:
      - mongo
    working_dir: /app
    build: .
    ports:
      - 3000:3000
      - 3001:3001
    command:
      - /bin/bash
      - -c
      - |
          source /usr/share/nvm/init-nvm.sh
          PATH=$PATH:~/.cargo/bin/
          cargo run --package artcord-builder
    environment:
      - CARGO_HOME=./cache
  mongo:
      image: mongo
      volumes:
        - "./mongo/db:/data/db"
      ports:
        - 27017:27017
  # web:
  #   depends_on:
  #     - mongo
  #   build: .
  #   working_dir: /app
  #   ports:
  #     - 3000:3000
  #     - 3001:3001
  #   volumes:
  #     - ".:/app"
  #   command:
  #     - /bin/bash
  #     - -c
  #     - |
  #         source /usr/share/nvm/init-nvm.sh
  #         cargo leptos watch