version: "3.1"
services:
  web:
    container_name: artcord_web
    volumes:
      - ".:/app"
    depends_on:
      - mongo
    entrypoint: /app/docker.sh
    working_dir: /app
    build: .
    ports:
      - 3420:3420
      - 3000:3000
      - 3001:3001
      - 8080:8080
    environment:
      - CARGO_HOME=./cache
      - RUST_LOG=artcord=trace
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
  mongo:
    image: mongo
    container_name: artcord_mongo
    volumes:
      - "./mongo/db:/data/db"
    ports:
      - 27017:27017
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
  # web:
  #   depends_on:
  #     - mongo
  #   build: .
  #   working_dir: /app
  #   ports:
  #     - 3000:3000
  #     - 3001:3001
  #   volumes:
  #     - ".:/app"
  #   command:
  #     - /bin/bash
  #     - -c
  #     - |
  #         source /usr/share/nvm/init-nvm.sh
  #         cargo leptos watch
