services:
  mongo:
    image: mongo
    volumes:
      - "./db:/data/db"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: U2L63zXot4n5
